// EVENT LISTENERS
var displayId = document.getElementById("display-container")
var searchButton = document.getElementById("search-button")
var searchInput2 = document.getElementById("input-search2")
var checkOut = document.getElementById("checkout")
var deleteItem = document.getElementById("cart")
var formSubmission = document.getElementById("formSubmit")
var back = document.getElementById("back")

searchButton.addEventListener('click', function(e){
  var itemSearched = document.getElementById("input-search").value.toLowerCase();
  search(itemSearched)
  display("items")
  hide("title-container")
  currentState = "items"
  e.preventDefault()
})

searchInput2.addEventListener('keypress', function(e){
  if(e.keyCode == 13){
    clearDom(displayId)
    search(this.value)
    e.preventDefault()
  }
})

checkOut.addEventListener('click', function(e){
  hide("items")
  display("payment-container")
  itemsInCart("cart");
  addDeleteEvent("cart")
  currentState = "payment"
  e.preventDefault();
})

formSubmission.addEventListener('click', function(e){
  formData()
  alert("Form Submitted!")
  e.preventDefault()
})

back.addEventListener('click', function(e){
  console.log(e)
  // toggleDisplay(e.target.id)
  e.preventDefault()
})

//FUNCTIONS
//MAIN TITLE CONTAINER PAGE

//Search the data object based on the input value of the user
var search = function(item){
  for(var i = 0; i<data.length; i++){
    if((data[i].category).indexOf(item) !== -1 || data[i].keyword == item){
      var prop = data[i]
      var productName = prop.name
      var highlights = prop.highlights
      var description = prop.description
      var id = prop.id
      var image = prop.image
      createItems(productName, highlights, description, id, image, "display-container")
      addEvent(id)
    }
  }
}

//ITEM DESCRIPTION PAGE
//Create several divs and columns that will append in the item container values from the data object.
var createItems = function(name, highlights, description, id ,image, elementContainer){
  var d = document
    , rowDiv = d.createElement("div")
    , colDiv1 = d.createElement("div")
    , colDiv2 = d.createElement("div")
    , list = d.createElement("li")
    , imgElement = d.createElement("img")
    , aLink = d.createElement("a")
    , hr = d.createElement("hr")
    , colText = d.createTextNode(name)
    , listText = d.createTextNode(description)
    , colText2 = d.createTextNode(highlights)
    , aLinkText = d.createTextNode("Add Cart")
    , aLinkText2 = d.createTextNode("Delete")
    , selectElement = d.createElement("select")
    , innerContainer = d.getElementById(elementContainer)

  var listFunction = function(array){
    for(i=0; i<array.length; i++){
      var list = d.createElement("li")
      var listText = d.createTextNode(array[i])
      list.appendChild(listText)
      colDiv2.appendChild(list)
    }
  }
  var appendFunction = function(row, col , rowClass, colClass, colText){
    row.className = rowClass
    col.className = colClass
    col.appendChild(colText)
    row.appendChild(col)
  }
  var selectFunction = function(select, value, colDiv){
    for(var i = 1; i<= value; i++){
      var optionName = "option" + i
      var optionName = d.createElement("option")
      optionName.value = i
      select.className = "quantity"
      optionName.appendChild(d.createTextNode(i))
      select.appendChild(optionName)
      colDiv.appendChild(select)
    }
  }

  var imgLinkFunction = function(imgElement, image, col, aLink, id){
    col.appendChild(imgElement)
    imgElement.src = image
    imgElement.className = "img-responsive img-test"
    aLink.id = id
    aLink.className = "padding-right"
    aLink.href = "#"
    col.appendChild(aLink)
    if(elementContainer == "display-container"){
      aLink.appendChild(aLinkText)
      selectFunction(selectElement, 5, colDiv1)
    } else {
      aLink.appendChild(aLinkText2)
    }
  }

  appendFunction(rowDiv, colDiv1, "row", "col-md-2 align-center box-size", colText)
  appendFunction(rowDiv, colDiv2, "row", "col-md-8 col-md-offset-1", colText2)
  imgLinkFunction(imgElement, image, colDiv1, aLink, id)
  listFunction(description)
  innerContainer.appendChild(rowDiv)
  innerContainer.appendChild(hr)
}

//AddEventListeners dynamically to each <a> tags generated by a search.
  var addEvent = function(id){
    var elementId = document.getElementById(id)
    var addedCount = document.getElementById("number")
    var itemObject = {}
    elementId.addEventListener('click', function(e){
      itemObject = {
        id: id,
        quantity: e.target.nextSibling.value
      }
      addedObjects.push(itemObject)
      addedCount.innerHTML = objectAddProperty(addedObjects, "quantity")
      e.preventDefault()
    })
  }

//PAYMENT-CONTAINER PAGE
//checks items added to the cart
var addedObjects = []
var itemsInCart = function(id_target){
  var sub_total = 0;
  for(var i = 0; i < addedObjects.length; i++){
    for(var j = 0; j < data.length; j++){
      if (addedObjects[i].id == data[j].id){
        var prop = data[j]
        var productName = prop.name
        var highlights = prop.highlights
        var description = prop.description
        var id = prop.id
        var image = prop.image
        sub_total += (prop.price * addedObjects[i].quantity);
        createItems(productName, highlights, description, id, image, id_target)
      }
    }
  }
  updateTotal(sub_total)
}

//addDelete Event Listener to each delete link elements.
var addDeleteEvent = function(id){
  var elementId = document.getElementById(id);
  elementId.addEventListener('click', function(e){
    if(e.target.nodeName == "A"){
      var itemToRemove = e.target.id
      var objectPosition = objectIndexOf(addedObjects, itemToRemove, "id")
      if(objectPosition > -1){
        addedObjects.splice(objectPosition, 1);
      }
    }
    clearDom(deleteItem)
    itemsInCart("cart")
  })
}

//Loops through the form elements creating an object of data to be sent off and processed
var formData = function(){
  form = document.getElementById("creditCard")
  var dataObject = {}
  var elements = form.elements
  for(var i = 0; i<elements.length; i++){
    dataObject[elements[i].id] = elements[i].value;
  }
  return dataObject
}

//Total price summed from within the cart
var updateTotal = function(sub_total){
  var subtotalSpan = document.getElementById("subtotal")
  var taxSpan = document.getElementById("tax")
  var shippingSpan = document.getElementById("shipping")
  var totalSpan = document.getElementById("total_sum")

  var tax = (sub_total * 0.08)
  var shipping = 25.00
  var total = (sub_total + tax + shipping)
  subtotalSpan.innerHTML = formatting(sub_total.toFixed(2))
  taxSpan.innerHTML = formatting(tax.toFixed(2))
  shippingSpan.innerHTML = formatting(shipping)
  totalSpan.innerHTML = formatting(total.toFixed(2))
}

//UTILITY FUNCTIONS

//Clear all childNodes as a new search is entered.
var clearDom = function(clearId){
  while(clearId.hasChildNodes()){
    clearId.removeChild(clearId.lastChild)
  }
}

//Hide containers
var hide = function(id){
  var element = document.getElementById(id)
  element.className = "hidden";
}

//Display containers
var display = function(id){
  var element = document.getElementById(id)
  element.classList.remove("hidden")
}

//Formatting for the numbers by adding commas
var formatting = function(number){
  var numToString = number.toString();
  var formatted = numToString >= 1000 ? '$' + numToString.charAt(0) + ',' + numToString.slice(1, numToString.length) : '$' + numToString
  return formatted
}

//Function for indexOf Objects
var objectIndexOf = function(objectArray, id, property){
  for(var i = 0; i < objectArray.length; i++){
    if(objectArray[i][property] == id){
      return i
    }
  }
  return -1
}

//Function for adding an array of object one single property.
var objectAddProperty = function(objectArray, property){
  var sum = 0
  for(var i = 0; i < objectArray.length; i++){
    sum += parseInt(objectArray[i][property])
  }
  return sum
}

//Function to determine if a class exists within an element classList.
var classExist  = function(array, name){
  for(var i = 0; i<array.length; i++){
    if(array[i] == name){
      return true
    }
  }
  return false
}


var addClass = function(array, name){
  if classExist(array, name){
    console.log("nothing was added")
    return false;
  } else {
    var string = name + ' '
    for(var i=0; i<array.length; i++){
      string += array[i]
    }
    return string
  }
}

var toggleDisplay = function(action, state){
  var containers = document.getElementsByClassName("container")
  var titleClasses = containers[0]
  var itemClasses = containers[1]
  var paymentClasses = containers[2]

  if(state == "title"){
    itemClasses.className = addClass(itemClasses.classList, "hidden")
    paymentClasses.className = addClass(paymentClasses.classList, "hidden")
  } else if(state == "items"){
    titleClasses.className = addClass(titleClasses.classList, "hidden")
    paymentClasses.className = addClass(paymentClasses.classList, "hidden")
  } else {
    titleClasses.className = addClass(titleClasses.classList, "hidden")
    itemClasses.className = addClass(itemClasses.classList, "hidden")
  }
  // console.log(titleClasses.classList)
}()
